dist: bionic
language: python

python:
  - "3.9"

# Custom directory, for the correct year
before_install:
  - cd 2019
  - python -m pip install --upgrade pip

script: pytest

cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
