[package]
name = "aoc-2021"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = "3.0.0-beta.5"
itertools = "0.10"
nom = "7"

[profile.release]
# Keep debug information in release for better flamegraphs
debug = true
