on:
  - push

name: Advent of Code 2023

jobs:
  ci:
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
        experimental: [false]
        include:
          - toolchain: nightly
            experimental: true

    name: Continuous Integration
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt

      - name: Set up caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: >
            2023 -> target

      - name: Build binaries
        working-directory: 2023
        run: >
          cargo build --all-targets

      - name: Run tests
        working-directory: 2023
        run: >
          cargo test

      - name: Check formatting
        working-directory: 2023
        run: >
          cargo fmt --check
